/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionarios;

import DB.ConnectMYSQL;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tduarte
*/
public class telaEntradaSaida extends javax.swing.JInternalFrame {

    ConnectMYSQL conex = new ConnectMYSQL();
    beansFuncionarios mod = new beansFuncionarios();
    daoFuncionarios control = new daoFuncionarios();
    
    
 
    
    
    public telaEntradaSaida() {
        initComponents();
        preencherTabela("select *from funcionarios order by usuario");  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Entrada e Saída");
        getContentPane().setLayout(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(611, 319, 150, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Ramal", "Nome" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(534, 317, 65, 24);

        jLabel7.setText("Foto-IMG");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(534, 196, 65, 115);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Todos)", "Copa", "Entrada Almoço", "Escritório", "Férias", "Foi embora", "Fora da mesa", "Licença", "Licença materinidade", "Médico", "Reunião", "Saída Almoço", "Saiu", "Sala de Reunião", "Viajando" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(611, 248, 130, 24);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Entrou", "Saiu", "Não Chegou" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(611, 196, 130, 24);

        jLabel6.setText("Foto");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(543, 175, 21, 15);

        jLabel8.setText("Tipo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(670, 175, 20, 15);

        jButton7.setText("Avisar-me quando chegar");
        jButton7.setEnabled(false);
        getContentPane().add(jButton7);
        jButton7.setBounds(220, 310, 200, 25);

        jLabel5.setText("Observação");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(61, 288, 60, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Copa", "Entrada Almoço", "Escritório", "Férias", "Foi Embora", "Fora da Mesa", "Licença", "Licença materinidade", "Médico", "Não chegou", "Reunião", "Saída Almoço", "Saiu", "Sala de Reunião", "Viajando" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(12, 258, 198, 24);

        jLabel4.setText("Movimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(68, 237, 51, 15);

        jTextField1.setText("16/11/2017");
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(49, 196, 58, 19);

        jLabel2.setText("Data:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 198, 25, 15);

        jLabel3.setText("Hora:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(119, 198, 26, 15);

        jTextField2.setText("04:01");
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(157, 196, 31, 19);

        jLabel1.setText("Status");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 175, 31, 15);

        jButton3.setText("OK");
        jButton3.setEnabled(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(216, 227, 100, 25);

        jButton1.setText("Entrada");
        getContentPane().add(jButton1);
        jButton1.setBounds(216, 197, 100, 25);

        jButton5.setText("Imprimir");
        jButton5.setEnabled(false);
        getContentPane().add(jButton5);
        jButton5.setBounds(216, 257, 100, 25);

        jButton6.setText("Participantes");
        jButton6.setEnabled(false);
        getContentPane().add(jButton6);
        jButton6.setBounds(321, 257, 100, 25);

        jButton4.setText("Cancelar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(321, 227, 100, 25);

        jButton2.setText("Saída");
        getContentPane().add(jButton2);
        jButton2.setBounds(321, 197, 100, 25);

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableFuncionarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 12, 764, 163);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(12, 309, 198, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
             public void preencherTabela(String Sql){
          ArrayList dados = new ArrayList();
          String [] colunas = new String []{"Usuario","Ramal","Nome Completo"};//ADD MOVIMENTO DPS
          conex.conectar();
          conex.executaSql(Sql);        
          try{
              conex.rs.first();
              do{
                  dados.add(new Object[] { conex.rs.getString("usuario"),conex.rs.getInt("ramal"),conex.rs.getString("nomecompleto")});
              }while(conex.rs.next());
          }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Erro ao preencher Arraylist"+ex); 
          }
          modeloTabela modelo = new modeloTabela(dados, colunas);
          
          jTableFuncionarios.setModel(modelo);
          jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(180);
          jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
          jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(180);
          jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
          jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(160);
          jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
          jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
          jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
          jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.desconecta();
      }
             
             
             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
