/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logando;

import DB.ConnectMYSQL;
import Funcionarios.beansFuncionarios;
import Funcionarios.daoFuncionarios;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author tduarte
 */
public class telaTrocaSenha extends javax.swing.JFrame {
    
    beansFuncionarios mod = new beansFuncionarios();
    daoFuncionarios control = new daoFuncionarios();
    ConnectMYSQL conex = new ConnectMYSQL();
    /**
     * Creates new form telaTrocaSenha
     */
    public telaTrocaSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_Usuario = new javax.swing.JTextField();
        jTextField_PassAntiga = new javax.swing.JTextField();
        jTextField_PassNova = new javax.swing.JTextField();
        jButton_Confirmar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jTextField_ConfirmarPassNova = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("IMG SENHA");

        jTextField_Usuario.setText("usuário");
        jTextField_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_UsuarioMouseClicked(evt);
            }
        });
        jTextField_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsuarioActionPerformed(evt);
            }
        });

        jTextField_PassAntiga.setText("senha antiga");
        jTextField_PassAntiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_PassAntigaMouseClicked(evt);
            }
        });

        jTextField_PassNova.setText("nova senha");
        jTextField_PassNova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_PassNovaMouseClicked(evt);
            }
        });

        jButton_Confirmar.setText("Confirmar");
        jButton_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jTextField_ConfirmarPassNova.setText("confirmar nova senha");
        jTextField_ConfirmarPassNova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ConfirmarPassNovaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_PassAntiga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(jTextField_PassNova, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jTextField_ConfirmarPassNova, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_PassAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_PassNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConfirmarPassNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Confirmar)
                            .addComponent(jButton_Cancelar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_UsuarioMouseClicked
        if(jTextField_Usuario.getText().equals("usuário")){
            jTextField_Usuario.setText("");
        }
    }//GEN-LAST:event_jTextField_UsuarioMouseClicked

    private void jTextField_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsuarioActionPerformed

    private void jTextField_PassAntigaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_PassAntigaMouseClicked
        if(jTextField_PassAntiga.getText().equals("senha antiga")){
            jTextField_PassAntiga.setText("");
        }
    }//GEN-LAST:event_jTextField_PassAntigaMouseClicked

    private void jTextField_PassNovaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_PassNovaMouseClicked
        if(jTextField_PassNova.getText().equals("nova senha")){
            jTextField_PassNova.setText("");
        }
    }//GEN-LAST:event_jTextField_PassNovaMouseClicked

    private void jTextField_ConfirmarPassNovaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ConfirmarPassNovaMouseClicked
        if(jTextField_ConfirmarPassNova.getText().equals("confirmar nova senha")){
            jTextField_ConfirmarPassNova.setText("");
        }
    }//GEN-LAST:event_jTextField_ConfirmarPassNovaMouseClicked

    public void limparCampos(String Type) {
        if("usr".equals(Type)) jTextField_Usuario.setText("");
        else if("oldsenha".equals(Type)) jTextField_PassAntiga.setText("");
        else if("newsenha".equals(Type)) {
            jTextField_PassNova.setText("");
            jTextField_ConfirmarPassNova.setText("");
        }
    }
    
    private void jButton_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarActionPerformed
        String usuario = jTextField_Usuario.getText();
        conex.executaSql("select * from funcionarios where usuario = '"+usuario+"'");
            try {
                conex.rs.first();
                if(mod.getSenha() != jTextField_PassAntiga.getText()) {
                    jTextField_PassAntiga.setText(conex.rs.getString("senha"));
                    JOptionPane.showMessageDialog(null, "Essa não é sua senha atual.");
                    limparCampos("oldsenha");
                }    
                if(jTextField_PassNova.getText().equals(jTextField_ConfirmarPassNova.getText())) {
                    PreparedStatement pst = conex.con.prepareStatement("update funcionarios set senha=? where usuario=?");
                    pst.setString   (1, mod.getSenha());
                    pst.setString   (2, mod.getUsuario());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucessos");
                }
                else {
                    limparCampos("newsenha");
                    JOptionPane.showMessageDialog(null, "As novas senhas não estão batendo.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Esse usuário não é um usuário valido.");
                limparCampos("usr");
            }
        
        conex.desconecta();
    }//GEN-LAST:event_jButton_ConfirmarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        telaLogin tlogin = new telaLogin();
        tlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaTrocaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_ConfirmarPassNova;
    private javax.swing.JTextField jTextField_PassAntiga;
    private javax.swing.JTextField jTextField_PassNova;
    private javax.swing.JTextField jTextField_Usuario;
    // End of variables declaration//GEN-END:variables
}
